/** Ikigai Pillar identifiers */
export type IkigaiPillar = 'love' | 'good' | 'need' | 'paid';

/** A single quiz question generated by AI */
export interface QuizQuestion {
  id: string;
  pillar: IkigaiPillar;
  question: string;
  options: string[];
  allow_other: boolean;
}

/** The full generated quiz */
export interface GeneratedQuiz {
  session_id: string;
  questions: QuizQuestion[];
  total_questions: number;
}

/** User's answer to a question */
export interface QuizAnswer {
  question_id: string;
  selected_option: string;
  is_custom: boolean;
}

/** Pillar score for the Radar chart */
export interface PillarScore {
  pillar: IkigaiPillar;
  label: string;
  score: number;
  max_score: number;
  description: string;
}

/** The Ikigai analysis result */
export interface IkigaiResult {
  archetype: string;
  archetype_description: string;
  pillar_scores: PillarScore[];
  strengths: string[];
  growth_areas: string[];
  guidance: string;
  action_steps: string[];
  summary_cards: SummaryCard[];
}

/** A single Spotify Wrapped-style summary card */
export interface SummaryCard {
  title: string;
  content: string;
  emoji: string;
  gradient: string;
}
